# Generated by Django 3.2 on 2023-05-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reflection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('Category', models.CharField(choices=[('It', 'IT業界'), ('backend', 'バックエンド'), ('other', 'その他')], max_length=100)),
            ],
        ),
    ]
