# Generated by Django 3.2 on 2023-05-10 10:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pdca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reflection',
            name='Action',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reflection',
            name='Check',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reflection',
            name='Do',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reflection',
            name='Plan',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
